
# clone directory
clone_folder: c:\projects\Log4Posh

before_build:
  - ps: |
      #nuget install platyPS -source https://www.powershellgallery.com/api/v2 -outputDirectory . -ExcludeVersion
      cinst -y pester --version 3.4.2
      cinst -y psake --version 4.6.0
      . $env:APPVEYOR_BUILD_FOLDER\Tools\Log4Posh_ProjectProfile.ps1
      Import-Module Psake
      
build_script:

- ps: . $env:APPVEYOR_BUILD_FOLDER\Tools\Build.ps1
