
# clone directory
clone_folder: c:\projects\Log4Posh

install:
  - ps: Install-PackageProvider Nuget -ForceBootstrap -Force
  - ps: Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
  - ps: Install-Module Pester -Force
  - ps: Install-Module PsScriptAnalyzer -force
  - ps: Install-Module Psake  -force
  
before_build:
  - ps:" 
       . $env:APPVEYOR_BUILD_FOLDER\Tools\Log4Posh_ProjectProfile.ps1
       Import-Module Psake
       "
build_script:

- ps: . $env:APPVEYOR_BUILD_FOLDER\Tools\Build.ps1
