
# clone directory
clone_folder: c:\projects\Log4Posh

install:
  - ps: | 
        Install-PackageProvider Nuget -ForceBootstrap -Force
        Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
        Install-Module Pester -Force
        Install-Module PsScriptAnalyzer -force
        Install-Module Psake  -force
  
before_build:
  - ps: | 
       . $env:APPVEYOR_BUILD_FOLDER\Tools\Log4Posh_ProjectProfile.ps1
       Import-Module Psake
       dir Variable:log4posh*||select Name,Value
       dir env:Appveyor*|Select Key,Value
build_script:

- ps: . $env:APPVEYOR_BUILD_FOLDER\Tools\Build.ps1
